services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - SHEET_ID=${SHEET_ID}
  caddy:
    build:
      context: $PWD/caddy
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${HOST_PORT}:443"
    volumes:
      - ./caddy:/etc/caddy/:ro
    environment:
      ACME_AGREE: 'true'